---
  - name: "Install extra packages repo"
    yum: 
      name: "{{ epel_src }}"
      state: present
  - name: "Install nginx"
    yum:
      name: "nginx"
      state: latest
  - name: "Set Nginx config"
    copy:
      src: app.conf
      dest: /etc/nginx/conf.d/app.conf
  - name: "Restarted NGiNX"
    service:
      name: nginx
      state: restarted