---
- hosts: proxy
  become: yes
  roles:
    - nginx
  
- hosts: application
  become: yes
  roles:
    - telegraf
    - app
  
- hosts: metrics
  become: yes
  roles:
    - influxDB
    - grafana
    - dashboard