---
  - name: "Install Telegraf"
    yum:
      name: "{{ telegraf_url }}"
      state: present
  - name: "Copy Telegraf configuration"
    template:
      src: telegraf.conf
      dest: /etc/telegraf/telegraf.conf
  - name: "restarted Telegraf"
    service:
      name: "telegraf"
      state: restarted
